# Generated by Django 4.2.6 on 2023-10-16 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='Event',
            name='privacy',
            field=models.CharField(default='private', max_length=30),
        ),
    ]
