# Generated by Django 4.2.3 on 2023-10-31 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_theme_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='test',
        ),
    ]
