# Generated by Django 4.2.6 on 2023-10-19 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_scavengerhunt_privacy_userprofile_player'),
        ('mainapp', '0003_event_privacy_userprofile'),
    ]

    operations = [
    ]
