# Generated by Django 4.2.6 on 2023-10-19 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_merge_20231019_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='privacy',
            field=models.CharField(choices=[('P', 'Private'), ('U', 'Public')], default='U', max_length=1),
        ),
    ]
