# Generated by Django 4.2.3 on 2023-10-20 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_event_privacy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='hunt',
            new_name='event',
        ),
        migrations.AlterField(
            model_name='event',
            name='privacy',
            field=models.CharField(choices=[('P', 'Private'), ('U', 'Public')], default='U', max_length=1),
        ),
    ]
