# Generated by Django 4.2.3 on 2023-10-29 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_rename_hunt_player_event_alter_event_privacy'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HuntTemplate',
            new_name='Theme',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='description',
            new_name='hint',
        ),
        migrations.RemoveField(
            model_name='task',
            name='location',
        ),
        migrations.AddField(
            model_name='event',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.theme'),
        ),
        migrations.AddField(
            model_name='task',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='task',
            field=models.TextField(default='THIS IS THE DEFAULT TASK VALUE AND SHOULD BE REPLACED'),
            preserve_default=False,
        ),
    ]
