# Generated by Django 4.2.6 on 2023-11-02 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_achievements'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
