# Generated by Django 4.2.6 on 2023-11-03 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0008_achievement_achievementearned_userprofile_points_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="achievementearned", name="earned",),
        migrations.RemoveField(
            model_name="achievementearned", name="user_achievement",
        ),
        migrations.AddField(
            model_name="achievement",
            name="points",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="achievementearned",
            name="achievement",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mainapp.achievement",
            ),
        ),
    ]
