# Generated by Django 4.2.6 on 2023-11-06 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0009_remove_achievementearned_earned_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="achievements",
            field=models.JSONField(null=True),
        ),
    ]
