# Generated by Django 4.2.6 on 2023-11-08 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0011_alter_userprofile_achievements"),
    ]

    operations = [
        migrations.RemoveField(model_name="userprofile", name="achievements",),
    ]
