# Generated by Django 4.2.6 on 2023-11-08 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0012_remove_userprofile_achievements"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="achievements",
            field=models.ManyToManyField(to="mainapp.achievementearned"),
        ),
    ]
