# Generated by Django 4.2.6 on 2023-11-11 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_userprofile_achievements'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='secret_key',
            field=models.CharField(default='default_key', max_length=100),
        ),
        migrations.AlterField(
            model_name='taskcompletion',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.task'),
        ),
    ]
