# Generated by Django 4.2.6 on 2023-11-12 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_remove_taskcompletion_completed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='secret_key',
            field=models.CharField(max_length=100),
        ),
    ]
