# Generated by Django 4.2.4 on 2023-11-12 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_alter_task_secret_key'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='team',
            unique_together={('name', 'event')},
        ),
    ]
