# Generated by Django 4.2.4 on 2023-11-12 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_alter_team_unique_together'),
        ('mainapp', '0017_team_points'),
    ]

    operations = [
    ]
