# Generated by Django 4.2.4 on 2023-11-29 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_userprofile_events_completed_alter_event_description'),
    ]

    operations = [

        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(max_length=350),
        ),
    ]
